apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-node-deployment
spec:
  selector:
    matchLabels:
      app: devops-node
  replicas: 1
  template:
    metadata:
      name: devops-node
      labels:
        app: devops-node
    spec:
      containers:
      - name: devops-node
        imagePullPolicy: Always
        image: x-image
        # envFrom:
        #   - configMapRef: 
        #       name: node-kube-config
