apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
images:
- name: x-image
  newName: rodrigov722/gitops-dev
  newTag: 6901dfb7b172309e0a1273b1388b72af3c6021f6
