FROM nginx:latest

WORKDIR /usr/share/nginx/html

RUN apt-get update

RUN apt-get install vim -y

COPY index.html /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]